apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-component
    app.kubernetes.io/part-of: node-application
  name: nodejs-componentsgxd
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nodejs-component
    weight: null
status: {}
